export async function imageFileToFold(file) {
  const bitmap = await createImageBitmap(file);
  const size = 256;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "white";
  ctx.fillRect(0, 0, size, size);
  const scale = Math.min(size / bitmap.width, size / bitmap.height);
  const width = bitmap.width * scale;
  const height = bitmap.height * scale;
  const ox = (size - width) / 2;
  const oy = (size - height) / 2;
  ctx.drawImage(bitmap, ox, oy, width, height);
  const image = ctx.getImageData(0, 0, size, size);
  const dark = darkPixels(image, size);
  const detected = detectDominantLines(dark, size);
  return linesToFold(detected);
}

function darkPixels(image, size) {
  const pixels = [];
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const i = (y * size + x) * 4;
      const gray = image.data[i] * 0.299 + image.data[i + 1] * 0.587 + image.data[i + 2] * 0.114;
      if (gray < 120) pixels.push([x, y]);
    }
  }
  return pixels;
}

function detectDominantLines(pixels, size) {
  const bins = {
    horizontal: new Map(),
    vertical: new Map(),
    diagDown: new Map(),
    diagUp: new Map(),
  };
  pixels.forEach(([x, y]) => {
    addBin(bins.horizontal, Math.round(y / 4) * 4);
    addBin(bins.vertical, Math.round(x / 4) * 4);
    addBin(bins.diagDown, Math.round((y - x) / 6) * 6);
    addBin(bins.diagUp, Math.round((y + x) / 6) * 6);
  });

  const threshold = Math.max(28, size * 0.18);
  return [
    ...topBins(bins.horizontal, threshold, 5).map((y) => ({ type: "h", value: y })),
    ...topBins(bins.vertical, threshold, 5).map((x) => ({ type: "v", value: x })),
    ...topBins(bins.diagDown, threshold, 4).map((d) => ({ type: "d", value: d })),
    ...topBins(bins.diagUp, threshold, 4).map((s) => ({ type: "u", value: s })),
  ];
}

function linesToFold(lines) {
  const vertices = [
    [0, 0],
    [1, 0],
    [1, 1],
    [0, 1],
  ];
  const edges = [
    [0, 1],
    [1, 2],
    [2, 3],
    [3, 0],
  ];
  const assignments = ["B", "B", "B", "B"];

  const addVertex = (point) => {
    const existing = vertices.findIndex((vertex) => Math.hypot(vertex[0] - point[0], vertex[1] - point[1]) < 0.015);
    if (existing >= 0) return existing;
    vertices.push(point);
    return vertices.length - 1;
  };

  lines.forEach((line, index) => {
    const segment = lineSegmentInUnitSquare(line);
    if (!segment) return;
    const a = addVertex(segment[0]);
    const b = addVertex(segment[1]);
    if (a !== b) {
      edges.push([a, b]);
      assignments.push(index % 2 === 0 ? "V" : "M");
    }
  });

  return {
    file_title: "Image CP import draft",
    solver_hint: "face-rigid-preview",
    fold_target_degrees: 90,
    vertices_coords: vertices,
    edges_vertices: edges,
    edges_assignment: assignments,
    faces_vertices: [[0, 1, 2, 3]],
    metadata: {
      note: "Generated by experimental image threshold/projection import. Review and split intersections before trusting it.",
      detected_lines: lines,
    },
  };
}

function lineSegmentInUnitSquare(line) {
  const n = (value) => Number(Math.max(0, Math.min(1, value / 255)).toFixed(4));
  if (line.type === "h") return [[0, n(line.value)], [1, n(line.value)]];
  if (line.type === "v") return [[n(line.value), 0], [n(line.value), 1]];
  if (line.type === "d") {
    const d = line.value / 255;
    return [[Math.max(0, -d), Math.max(0, d)], [Math.min(1, 1 - d), Math.min(1, 1 + d)]].map(([x, y]) => [Number(x.toFixed(4)), Number(y.toFixed(4))]);
  }
  if (line.type === "u") {
    const s = line.value / 255;
    return [[Math.max(0, s - 1), Math.min(1, s)], [Math.min(1, s), Math.max(0, s - 1)]].map(([x, y]) => [Number(x.toFixed(4)), Number(y.toFixed(4))]);
  }
  return null;
}

function addBin(map, key) {
  map.set(key, (map.get(key) || 0) + 1);
}

function topBins(map, threshold, count) {
  return Array.from(map.entries())
    .filter(([, value]) => value >= threshold)
    .sort((a, b) => b[1] - a[1])
    .slice(0, count)
    .map(([key]) => key);
}
